### PR TITLE
Get GitHub, GitHubPR, GitHubUser info from JSON

### PR DESCRIPTION
**Pull request by SD10**
Hey @orta,
I tried implementing some of your pseudo-code. Sorry if this wasn't what you had in mind or if I'm stepping on your toes 😅

### CODE REVIEW

**Comment by orta** [comment]
amazing, not stepping on toes - I just put that there by copying & pasting from the website - great job

**Comment by SD10** [comment]
@orta Thanks, let me know if there's anything else I can help with. 
Do you want me to write tests for the decoded data?

**Comment by orta** [comment]
Sure, I'd like to see some tests for this stuff - I've been in prototype mode, but it's feeling close to being workable now so I'm gonna spend some more time on the Danger JS side so that I can do full integration tests.

**Comment by SD10** [comment]
Sure, I can only assist on the Swift end of things. If I can eat up any of the Swift work it will give you more time to focus on Danger JS domain specific issues.

**Comment by orta** [comment]
Yeah, that's totally awesome

**Comment by orta** [comment]
I've wrote up some short term issues that will pop up

**Pull request merged**
