### PR TITLE
Update Marathon version

### LINKED ISSUE #63: danger-swift is incompatible with swift 4.1
When launching on a machine with xcode 9.3 (swift 4.1) I got this error:
```bash
danger process danger-swift
dyld: Symbol not found: __T0SayxGs9DecodableslWP
  Referenced from: /usr/local/bin/danger-swift
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib
 in /usr/local/bin/danger-swift

events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:844:14)
Emitted 'error' event at:
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:453:5)
    at _destroy (internal/streams/destroy.js:39:7)
    at Socket._destroy (net.js:548:3)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:846:10)
script returned exit code 1
```

Probably, https://github.com/RxSwiftCommunity/Action/pull/118 may help to resolve this issue.

### PR DESCRIPTION
**Pull request by sunshinejr**
This should fix #63 && #64. We would need brew release as well (never really did it so not sure how long the process is).

### CODE REVIEW

**Comment by Sega-Zero** [comment]
Shouldn't `.travis.yml` be updated to `swiftenv global 4.1` too?

**Comment by sunshinejr** [comment]
Oh, good point @Sega-Zero, thanks! Fixing as we speak.

**Comment by Sega-Zero** [comment]
Looks like Files version should bу set to 2.2.1 :)

**Comment by sunshinejr** [comment]
Huh, finally green 😅 Thanks for the help @Sega-Zero, I was really confused when FIles didn't want to compile, not sure why `Package.resolved` didn't get the newest package versions but cleaning it all and installing again did the trick!

**Comment by orta** [comment]
Looks good to me 😀 👍

**Comment by orta** [comment]
We're blocked on shipping this dues to home-brew though right/ (for installation of danger-swft)

**Comment by sunshinejr** [comment]
@orta What I meant in the description is that after the merge we should release this on Homebrew as well (I've no experience doing it so didn't know if I should include some changes in order to make the release on Homebrew easier).

Unless it's not what you're asking 😅

**Comment by orta** [comment]
Ah sure, yeah, that's trivial

**Comment by orta** [comment]
I'll let you give it a try, docs are in the README, usually takes me about 60 seconds (obviously it'll take you a bit longer)

**Comment by sunshinejr** [comment]
Oh, sure, gonna give it a go!

**Comment by sunshinejr** [comment]
Released in 0.3.6 - seems like it's working using Homebrew already, did a check on Harvey: https://circleci.com/gh/Moya/Harvey/220

**Pull request merged**
