### PR TITLE
Add DangerTests target

### PR DESCRIPTION
**Pull request by SD10**
This adds a `DangerTests` target and updates `Package.swift`

### CODE REVIEW

**Comment by orta** [comment]
Rockin' - I added a `travis.yml` - so it should be trivial to hook it up on CI too 👍

**Comment by orta** [comment]
And I've invited you to the org 👍

**Comment by orta** [comment]
You're welcome to merge this when you want

**Comment by SD10** [comment]
Great thanks 👍 😄

**Pull request merged**
