### PR TITLE
Run CI on Linux

### PR DESCRIPTION
**Pull request by SD10**
I'm not sure if its as easy as this:
https://swiftenv.fuller.li/en/latest/integrations/travis-ci.html

### CODE REVIEW

**Comment by orta** [comment]
Him, I have no idea what that's about

**Comment by orta** [comment]
screen shot 2017-09-04 at 14 51 03
I also get weird errors in https://github.com/JohnSundell/Marathon/pull/127

**Comment by SD10** [comment]
Yeah, I have no idea what these errors are from. I'll keep looking into this

**Comment by SD10** [comment]
@orta Our `Swift.package` requires a Swift tools version of `4.0` but we have Swift 3 declared under `swiftLanaguageVersions`. Is this accurate?

**Comment by orta** [comment]
I guess it depends on your perspective, Swift 4 has both Swift 3 and 4 inside the compiler. TBH though, 4 is a better call there

**Comment by orta** [comment]
Maybe try stealing  this: https://github.com/vapor/vapor/blob/master/circle.yml

**Comment by SD10** [comment]
Thanks for picking up my slack 😅 ❤️

**Comment by orta** [comment]
Heyyyy, that's it working 👍

**Pull request merged**
